### ISSUE TITLE
Legacy mappings?

### ISSUE THREAD

**Issue by Zilacon** [Aizistral-Studios/MCP-Archive#2]
Hello, we are looking for MCP for 1.5.2 and 1.6.4 do you have those?
Thanks

**Comment by Aizistral** [comment]
Not here. They were never published on [export.mcpbot.bspk.rs](http://export.mcpbot.bspk.rs) or Forge's maven, and as far as I'm aware they can only be obtained with MCP itself (the list of MCP versions along with download links can be found [here](https://minecraft.fandom.com/wiki/Programs_and_editors/Mod_Coder_Pack)). If you will - you could help this archival project by catalogizing and submitting those older mappings through a PR.

**Comment by Zilacon** [comment]
Alright thanks.
